def vocab(v):
    v['name'] = [
        'Brooklyn',
        'Etsy',
        'Helvetica',
        'Pitchfork',
        'Shoreditch',
        'Tumblr',
        'Wes Anderson',
        'Williamsburg',
        '3 Wolf Moon',
    ]
    v['noun'] = [
        'art party; art parties',
        'bicycle; ~s',
        'cardigan; ~s',
        'chambray; ~s',
        'Cosby sweater; ~s',
        'dreamcatcher; ~s',
        'fixie; ~s',
        'hoodie; ~s',
        'iPhone; ~s',
        'keffiyah; ~s',
        'keytar; ~s',
        'messenger bag; ~s',
        'mixtape; ~s',
        'moustache; ~s',
        'PBR',
        'quinoa',
        'vinyl record; vinyl',
        'skateboard; ~s',
    ]
    v['adj'] = [
        'American Apparel',
        'denim',
        'Etsy',
        'freegan',
        'gluten-free',
        'ironic',
        'lo-fi',
        'lomo',
        'organic',
        'readymade',
        'retro',
        'scenester',
        'sustainable',
        'tattooed',
        'tofu',
        'VHS',
        'vintage',
        'vinyl',
    ]
    v['iverb'].append([
        'sell out; sells out; sold out; ~; selling out',
    ]);
    return v
