# vim: set fileencoding=utf-8 :

__author__ = 'Liam Cooke <http://boxofjunk.ws/>'

from common import *

spengbab = lambda: choice(\
        ['Spange','Speng','Sporg','Splorg','Spang',
        'Spernd','Splort','Spunk','Scram','Spange','Speeng',
        'Splen','Spengj','Spinge','Spong']\
        ) + choice(\
        ['bob','bob','bob','bab','bab','beb','blat','berp','bharb',
        'blar','borg'])
sqarpents = lambda: choice(\
        ['Sqar','Skur','Sven','Squat','Spleen','Snare','Sklabh',
        'Squere','Dildo']\
        ) + choice(\
        ['pents','ponce','porks','peeps','pops','pans','pints',
        'ponts'])

vocab = {
    'spengbab': [
        lambda: '%s %s' % (spengbab(), sqarpents()),
    ],

    'name': [
        'Abbath',
        'Abe Vigoda',
        'Acid Burn',
        'Anonymous',
        'AOL',
        'Apple',
        'Battletoads',
        'Bill Gates',
        'Burzum',
        'Buzzfeed',
        'Catwoman',
        'Chuck Testa',
        'Crash Override',
        'Dagron',
        'Dethklok',
        'Dickbutt',
        'Digg',
        'Domokun',
        'Dragonforce',
    'The Dude',
        'Duke Nukem',
        'Dumbledore',
        'Elvis',
        'Facebook login',
    'The FBI',
    'The Flying Spaghetti Monster',
        'FOX News',
    'The Fresh Prince',
        'George Bush',
        'G.I. Joe',
        'Goatse',
        'God',
        'Google',
        'Google Glass',
        'Harry Potter',
        'Homer',
        'Imhotep',
        'Jawsus',
        'Jean-Luc Picard',
        'Jesus',
        'Jimmy Wales',
        'John Freeman',
        'John Romero',
        'Kanye West',
        'Keyboard Cat',
        'KOMPRESSOR',
        'Kotaku',
        'Lars Ulrich',
        'Lil Jon',
        'Longcat',
        'Luigi',
        'Mario',
        'Maru',
        'Metallica',
        'Michael Jackson',
        'Microsoft',
        'Milhouse',
        'moot',
    'The music industry',
        'Nine Inch Nails',
        'Nod Flenders',
    'The NSA',
        'Obama',
        'Pinterest',
    'The Pirate Bay',
        'Raptorjesus',
        'Reddit',
    'The RIAA',
        'Richard Stallman',
        'Scientology',
        'Serious Cat',
        'Skrillex',
        'Snapchat',
        'Snowden',
        'Spengbab',
        'Spiderman',
        'Star Wars',
        'Star Wars Kid',
        'Steve Ballmer',
        'Superboy',
        'Superman',
        'Superwoman',
        'Thrillho',
        'Trent Reznor',
        'Trogdor',
        'Tron Guy',
        'Tumblr',
        'Twitter',
        'Weegee',
        'Wikileaks',
        'Woll Smoth',
        'W.T. Snacks',
        'Xenu',
        'Xzibit',
        'YouTube',
        'Zalgo',
        'Za Warudo',
        'Zero Cool',
        'Zoidberg',
        lambda: '%s %s' % (spengbab(), sqarpents()),
        lambda: 'Spengbab %s' % sqarpents(),
    ],

    'noun': [
        'alien; ~s',
        'animated gif; ~s',
        'anime',
        'anime video; ~s',
        'ant; ~s',
        'apple; ~s',
        'arse eel; ~s',  # apologies to Warren Ellis
        'asteroid; ~s',
        'atheist; ~s',
        'babby; ~s',
        'bacon',
        'balloon; ~s',
        'bank; ~s',
        'banker; ~s',
        'bear; ~s',
        'bed; ~s',
        'bee; ~s',
        'beer; ~s',
        'bird; ~s',
        'blogger; ~s',
        'boat; ~s',
        'bone; ~s',
        'book; ~s',
        'bucket; ~s',
        'button; ~s',
        'cake; ~s',
        'car; ~s',
        'castle; ~s',
        'cat; ~s',
        'centipede; ~s',
        'cheat code; ~s',
        'Coca-Cola bottle; ~s',
        'coffee; ~s',
        'coin; ~s',
        'comic; ~s',
        'computer; ~s',
        'cookie; ~s',
        'copypasta',
        'cow; ~s',
        'dad; ~s',
        'demon; ~s',
        'dictionary; dictionaries',
        'dinosaur; ~s',
        'doctor; ~s',
        #'dog; ~s',
        'doge; ~s',
        'donut; ~s',
        'door; ~s',
        'dragon; ~s',
        'drink; ~s',
        'drug; ~s',
        'duck; ~s',
        'dude; ~s',
        'eel; ~s',
        'emo; ~s',
        'eskimo; ~s',
        'extra life; extra lives',
        'Facebook profile; ~s',
        'fish',
        'fist; ~s',
        'forest; ~s',
        'gamer; ~s',
        'garbage file; ~s',
        'gibson; ~s',
        'girl; ~s',
        'girlfriend; ~s',
        'goat; ~s',
        'goth; ~s',
        'government; ~s',
        'grammar; ~s',
        'grandspasguitar; ~s',
        'guitar; ~s',
        'guy; ~s',
        'hacker; ~s',
        'hacker on steroids; hackers on steroids',
        'hat; ~s',
        'h4x0r; ~z',
        'hero; ~es',
        'horse; ~s',
        'house; ~s',
        'hovercraft; ~s',
        'human; ~s',
        'ice cream',
        'insect; ~s',
        'interior crocodile alligator; ~s',
        'internet; ~s',
        'IPHONE; ~s',
        'iPad; ~s',
        'iPod; ~s',
        'jedi; ~s',
        'jedi knight; ~s',
        'junk',
        'keyboard; ~s',
        'kitten; ~s',
        'large hadron collider; ~s',
        'lawyer; ~s',
        'leprechaun; ~s',
        'Linux user; ~s',
        'lion; ~s',
        'LiveJournal; ~s',
        'llama; ~s',
        'lulz',
        'MacBook; ~s',
        'MacBook Air; ~s',
        'manga',
        lambda: 'megah%srtz' % choice('ue'),
        'mom; ~s',
        'moron; ~s',
        'mp3 file; ~s',
        'mudkip; ~z',
        'music; ~ videos',
        'MySpace; ~ angles',
        'MySpace profile; ~s',
        'MySpace password; seven different passwords',
        'nerd; ~s',
        'ninja; ~s',
        'panda; ~s',
        'password; ~s',
        'penguin; ~s',
        'photographer; ~s',
        'pig; ~s',
        'pirate; ~s',
        'pizza',
        'planet; ~s',
        'plank; ~s',
        lambda: 'Pokem%sn; Pokemans' % choice('oa'),
        'poop',
        'potato; ~es',
        'rainbow; ~s',
        'record label; ~s',
        'robot; ~s',
        'rocket; ~s',
        'sandwich; ~es',
        'sausage; ~s',
        'scientologist; ~s',
        'script-kiddie; ~z',
        lambda: '%s; ~s' % choice(('shibe', 'shibe doge')),
        'shoe; ~s',
        'skittle; ~s',
        'snake; ~s',
        'snowman; snowmen',
        'song; ~s',
        'spoon; ~s',
        'superhero; ~es',
        'Tamagotchi; ~s',
        'techno weenie; ~s',
        'tentacle; ~s',
        'torrent; ~s',
        'troll; ~s',
        'TV; ~s',
        'unicorn; ~s',
        'videogame; ~s',
        'vidja gaem; ~s',
        'wart; ~s',
        'webcam; ~s',
        'whale; ~s',
        'windmill; ~s',
        'window; ~s',
        'Windows user; ~s',
        'xbox; ~es',
        'YouTube comment; ~s',
        'YouTube video; ~s',
        'zombie; ~s',
    ],

    'bodypart': [
        'afro; ~s',
        'arm; ~s',
        'armpit; ~s',
        'ass; ~es',
        'beard; ~s',
        'butt; ~s',
        'dong; ~s',
        'ear; ~s',
        'eye; ~s',
        'finger; ~s',
        'foot; feet',
        'hand; ~s',
        'head; ~s',
        'leg; ~s',
        'lip; ~s',
        'moustache; ~s',
        'mouth; ~s',
        'mullet; ~s',
        'neckbeard; ~s',
        'nose; ~s',
        'nostril; ~s',
        'toe; ~s',
        'tongue; ~s',
        'wang; ~s',
        'wiener; ~s',
    ],

    # transitive verbs (object)
    'verb': [
        # I write; He writes; I wrote; I have/had written; I am/was writing
        'accidentally; ~; ~; ~; ~',
        'bobba; ~; ~; ~; ~',
        'burn; ~s; burned; ~; burning',
        'boot up; boots up; booted up; ~; booting up',
        'clean; ~s; cleaned; ~; cleaning',
        'cook; cooks; cooked; ~; cooking',
        'defenestrate; ~s; defenestrated; ~; defenestrating',
        'destroy; ~s; destroyed; ~; destroying',
        'discombobulate; ~s; discombobulated; ~; discombobulating',
        'drink; ~s; drank; drunk; drinking',
        'download; ~s; downloaded; ~; downloading',
        'eat; ~s; ate; eaten; eating',
        'google; ~s; googled; ~; googling',
        'hack; ~s; hacked; ~; hacking',
        'h4x0r; ~z; h4x0r3d; ~; hacking',
        'kick; ~s; kicked; ~; kicking',
        'kill; ~s; killed; ~; killing',
        'masticate; ~s; masticated; ~; masticating',
        'photoshop; ~s; photoshopped; ~; photoshopping',
        'pop; ~s; popped; ~; popping',
        'punch; ~es; punched; ~; punching',
        'shoop; ~s; shooped; ~; shooping',
        'shoot; ~s; shot; ~; shooting',
        'steal; ~s; stole; stolen; stealing',
        'throw; ~s; threw; thrown; throwing',
        'torrent; ~s; torrented; ~; torrenting',
        'troll; ~s; trolled; ~; trolling',
        'watch; ~es; watched; ~; watching',
    ],

    # intransitive verb (no object)
    'iverb': [
        # I write; He writes; I wrote; I have/had written; I am/was writing
        'bail out; bails out; bailed out; ~; bailing out',
        'blog; ~s; blogged; ~; blogging',
        'chew bees; chews bees; chewed bees; ~; chewing bees',
        'count; ~s; counted; ~; counting',
        'dance; ~s; danced; ~; dancing',
        'do a barrel roll; does a barrel roll; did a barrel roll; '\
                'done a barrel roll; doing a barrel roll',
        'download mp3s; downloads mp3s; downloaded mp3s; ~; downloading mp3s',
        'drink; ~s; drank; drunk; drinking',
        'drive; ~s; drove; driven; driving',
        'duck; ~s; ducked; ~; ducking',
        'eat; ~s; ate; eaten; eating',
        'fart; ~s; farted; ~; farting',
        'frigth back; frigths back; frigth back; ~; frigthing back',
        'get low; gets low; got low; gotten low; getting low',
        'hack; ~s; hacked; ~; hacking',
        'krump; ~s; krumped; ~; krumping',
        "lol; ~s; lol'd; ~; lollin",
        'lurk moar; lurks moar; lurked moar; lurked moar; lurking moar',
        'moonwalk; ~s; moonwalked; ~; moonwalking',
        'nyan; ~s; nyaned; ~; nyaning',
        'pop; ~s; popped; ~; popping',
        'roar; ~s; roared; ~; roaring',
        'run; ~s; ran; run; running',
        'scream; ~s; screamed; ~; screaming',
        'shoop; ~s; shooped; ~; shoopin',
        'sing; ~s; sang; sung; singing',
        'suck; ~s; sucked; ~; sucking',
        'troll; ~s; trolled; ~; trolling',
        'whine; ~s; whined; ~; whining',
    ],

    'adj': [
        'angry',
        'awkward',
        'bald',
        'broken',
        'crunk',
        'delicious',
        'dizzy',
        'drunk',
        'emo',
        'epic',
        'flying',
        'forever alone',
        'hairy',
        'grim',
        'grim and frostbitten',
        'hairy',
        'homeless',
        'HUEG',
        'illegal',
        'inverted',
        'invisible',
        'juicy',
        'keyboard',
        'kvlt',
        'l33t',
        'large',
        'lazy',
        'long',
        'mighty',
        'necro',
        'old',
        lambda: 'o' * randint(3,8) + 'ld',
        'photoshopped',
        'pig disgusting',
        'pirated',
        'pointing',
        'raging',
        'screaming',
        'sentient',
        'serious',
        'slow',
        'spicy',
        'successful',
        'sweaty',
        'tall',
        'tiny',
        'tl;dr',
        'trve kvlt',
        'ugly',
        'vegetarian',
        'weak',
    ],
}

vocab['noun'].extend(vocab['bodypart'])
